env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
database:
  username: "postgres"
  host: "localhost"
  port: 5432
  db_name: "postgres"
  ssl_mode: "disable"
